# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/xuzhiyuan/Desktop/login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 357)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(500, 300))
        Form.setMaximumSize(QtCore.QSize(500, 400))
        Form.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/xuzhiyuan/Desktop/images/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color:rgb(181, 212, 255)")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(151, 90, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.edit_username = QtWidgets.QLineEdit(Form)
        self.edit_username.setGeometry(QtCore.QRect(160, 150, 181, 31))
        self.edit_username.setObjectName("edit_username")
        self.edit_password = QtWidgets.QLineEdit(Form)
        self.edit_password.setGeometry(QtCore.QRect(160, 200, 181, 31))
        self.edit_password.setObjectName("edit_password")
        self.btn_login = QtWidgets.QPushButton(Form)
        self.btn_login.setGeometry(QtCore.QRect(120, 310, 81, 31))
        self.btn_login.setObjectName("btn_login")
        self.btn_regeist = QtWidgets.QPushButton(Form)
        self.btn_regeist.setGeometry(QtCore.QRect(330, 310, 81, 31))
        self.btn_regeist.setObjectName("btn_regeist")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 10, 500, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("UI/UI_Resource/Footer_Logo.png"))
        self.label_3.setObjectName("label_3")
        self.checkBox_Online = QtWidgets.QCheckBox(Form)
        self.checkBox_Online.setGeometry(QtCore.QRect(360, 105, 85, 21))
        self.checkBox_Online.setObjectName("checkBox_Online")
        self.edit_password_verify = QtWidgets.QLineEdit(Form)
        self.edit_password_verify.setGeometry(QtCore.QRect(160, 250, 71, 31))
        self.edit_password_verify.setObjectName("edit_password_verify")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(240, 250, 101, 31))
        self.label.setText("")
        self.label.setObjectName("label")
        self.btn_regeist_2 = QtWidgets.QPushButton(Form)
        self.btn_regeist_2.setGeometry(QtCore.QRect(360, 260, 75, 23))
        self.btn_regeist_2.setObjectName("btn_regeist_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录"))
        self.label_2.setText(_translate("Form", "口罩检测识别系统"))
        self.edit_username.setPlaceholderText(_translate("Form", "用户名"))
        self.edit_password.setPlaceholderText(_translate("Form", "密码"))
        self.btn_login.setText(_translate("Form", "登录"))
        self.btn_regeist.setText(_translate("Form", "注册"))
        self.checkBox_Online.setText(_translate("Form", "云端检测"))
        self.edit_password_verify.setPlaceholderText(_translate("Form", "验证码"))
        self.btn_regeist_2.setText(_translate("Form", "刷新验证码"))
